### ISSUE TITLE
sumTransactionItemIndicator arithmetic failure 

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial-web#17]
**Steps**
1. Sign into account to display homeScreen.
2. Add milk, 2.00, 1 item.
3. Add bread, 3.00, 2 item.
4. Add honey, 4.00, 3 item.
5. Delete milk item.

**Observed**: Total = 6

**Expected**: Total = 18

@enesTufekci 
1. This is not reproduced in master prior to refactor.
2. Please add automated test for this case. Manual testing is expensive. Please help avoid.

**Comment by mxfactorial** [comment]
Occurs on `request-screen` branch.
Added the `automatable` and `automated` issue labels. 
Beginning with this issue, please add `automatable` label to any requirement judged clear enough to be covered by test automation. If not clear enough, please ask questions to reduce incomplete information until `automatable` may be added.
After commenting commit link to automated test(s), please add `automated` label to any requirement covered by test automation.

**Comment by enesTufekci** [comment]
https://github.com/systemaccounting/mxfactorial-web/pull/14/commits/ac78574e3f8b01df88e00ff3bd1e65f3e40498cb

**Comment by enesTufekci** [comment]
will be fixed with #14

**Comment by mxfactorial** [comment]
Code and test still broken @enesTufekci 

![arithmetic-failure-2](https://user-images.githubusercontent.com/12200465/45592024-333fb680-b917-11e8-8c2e-e23a4aa8d8ab.gif)

**Comment by enesTufekci** [comment]
[draft transaction](https://github.com/systemaccounting/mxfactorial-web/pull/14/commits/e517ee0948147dad21ec5bce59c8d85281ece3f9) commit solved this problem. Also unit and e2e tests added.

**Comment by mxfactorial** [comment]
Accepted in https://github.com/systemaccounting/mxfactorial-web/pull/14
