### ISSUE TITLE
Delete transaction item failure

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial-web#18]
**Steps**

1. Sign into account to display homeScreen.
2. Add milk, 2.00, 1 item.
3. Add bread, 3.00, 2 item.
4. Add honey, 4.00, 3 item.
5. Delete milk item.

**Observed**: bread item removed. milk and honey items remain.

**Expected**: milk item removed. bread and honey items remain.

@enesTufekci

This is not reproduced in master prior to refactor.
Please add `automatable` label if information is complete, then add `automated` label and commit link after covering with test automation.

**Comment by mxfactorial** [comment]
Occurs on `request-screen` branch.

**Comment by enesTufekci** [comment]
https://github.com/systemaccounting/mxfactorial-web/pull/14/commits/ac78574e3f8b01df88e00ff3bd1e65f3e40498cb

**Comment by enesTufekci** [comment]
this will be fixed with #14

**Comment by mxfactorial** [comment]
Accepted in https://github.com/systemaccounting/mxfactorial-web/pull/14
