### ISSUE TITLE
Transaction item greater than 0 failure

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial-web#20]
**Branch**: `request-screen`
**Client**: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
**OS**: Mac OS 10.12.6 (16G1408)

**Steps**
1. Sign into account to display homeScreen.
2. Add milk, 2.00, 2 quantity item.
3. Add bread, 3.00, 3 quantity item.
4. Select bread deleteItemButton to display draft transaction.
5. Select draft transaction deleteItemButton to delete draft transaction item.
6. Select milk deleteItemButton.

**Observed**: 0 draft transaction items display (33% zoom in .gif; ignore debit and credit button sizes).

![2018-09-20 22 09 53](https://user-images.githubusercontent.com/12200465/45862032-bd778880-bd24-11e8-8309-9d02acb39fd0.gif)

**Expected**: 1 draft transaction item displays (see pre-refactor `git checkout d66af0b2d0b4d6ef8fb49fb2fb532820d4373978`).

![2018-09-20 22 12 14](https://user-images.githubusercontent.com/12200465/45862044-c700f080-bd24-11e8-92a2-b8940adf834d.gif)

Regression bug since pre-refactor, and missing test automation coverage since "2. Please fix and add e2e coverage for items.length > 0" from [comment 411647867 on pull request 8](https://github.com/systemaccounting/mxfactorial-web/pull/8#issuecomment-411647867).

**Next steps**:
1. Add `automatable` github issue label if you have 0 questions about how to automate this case
2. Add links to `request-screen` branch commits of fix and automated test for this case

**Comment by enesTufekci** [comment]
e2e : https://github.com/systemaccounting/mxfactorial-web/blob/4fe97718279c5d7599a971172f450a3edb196473/e2e/homeScreen/formVisibility.test.js#L29

unit: https://github.com/systemaccounting/mxfactorial-web/blob/4fe97718279c5d7599a971172f450a3edb196473/src/screens/HomeScreen/__tests__/Transaction.test.js#L164

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial-web/pull/14
