### ISSUE TITLE
Initial refactoring

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial-web#7]
1. Add `reach-router`
2. Add `styled-components`
3. separate `components` from `containers`
4. Improve unit test design

**Comment by enesTufekci** [comment]
Estimation: 5h

**Comment by mxfactorial** [comment]
Approved. Please reference this issue in pull request when available.

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial-web/pull/8
