### ISSUE TITLE
Add data model to client state

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial-web#9]
Prepare for API consumption by adding data model described in https://github.com/systemaccounting/mxfactorial-web/blob/73582e990d25194ae76111bf131020462adea4d4/src/containers/HomeScreen/README.md#transaction-model to client state.

**Comment by enesTufekci** [comment]
Estimation 1h

**Comment by mxfactorial** [comment]
Approved, please link PR when convenient.

**Comment by enesTufekci** [comment]
PR ready #10

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial-web/pull/10
